jobs:
  runs:
    build-app:
      NEXT_PUBLIC_INSTAGRAM_TOKEN: instagram_token_prod
      NEXT_PUBLIC_API_URL: https://backoffice-les1000jours.fabrique.social.gouv.fr

app:
  resources:
    requests:
      cpu: 100m
      memory: 386Mi
    limits:
      cpu: 200m
      memory: 512Mi
