name: Review

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  deploy:
    name: Deploy review branch
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Use autodevops to deploy review branch
        uses: SocialGouv/actions/autodevops-helm@v1
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          imageName: nos1000jours/nos1000jours-blues
          baseNamespace: env-1000jours-blues
          baseSubdomain: env-1000jours-blues
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
          dockerbuildargs: |
            NEXT_PUBLIC_INSTAGRAM_TOKEN=instagram_token_dev
